---
title: "Partial Solution"
output: bookdown::html_document2
date: 'Last compiled: `r format(Sys.time(), "%B %d, %Y")`'
csl: acta-astronautica.csl 
bibliography: Alayna.bib
link-citations: true
---



```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", comment = NA, message = FALSE, warning = FALSE)
library(plotly)
library(tidyverse)
library(lubridate)
library(zoo)  # for rollmean
```


**Exercise 1.**

```{r}
# Exercise 1.
# read in data
covid_data_pop <- read_csv("./data/covid_data_pop.csv")
covid_data <- read_csv("./data/covid_data.csv")
```

_____________

**Exercise 2.**

```{r, label = "deathsLOG", fig.cap = "World wide reported COVID-19 deaths (logarithmic base 10 scale) by date"}
# Exercise 2.
covid_data %>% 
  group_by(date) %>% 
  summarise(dead = sum(dead)) %>% 
  ggplot(aes(x = date, y = dead)) +
    geom_line(color = 'orange') +
    geom_point(color = "orange", size = 1) +  
    theme_bw() + 
    scale_y_log10()
```

__________

**Exercise 3.**

```{r}
# Exercise 3.
covid_data %>% 
  ggplot(aes(x = date, y = new_cases)) +
    geom_bar(stat="identity", fill = "orange") + 
    labs(y = "New Cases") +
    theme_bw()
```

Note that some of the `New Cases` are negative!  We will fix that next.

```{r, label = "noneg", fig.cap = "New Cases by date"}
# Exercise 3.  Final Solution
covid_data %>% 
  mutate(new_cases = ifelse(new_cases < 0, 0, new_cases)) %>% 
  ggplot(aes(x = date, y = new_cases)) +
    geom_bar(stat="identity", fill = "orange") + 
    labs(y = "New Cases") +
    theme_bw()
```

____________

**Exercise 4.**

Here we practice citing the work of [@lahey_public_2009] and discuss how [@gehring_prefrontal-cingulate_2000; @savitz_personality_2006] wax eloquently.

______________

## References

